name: run lighthouse and upload

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - name: install
        run: yarn install
      - name: run lh
        run: yarn run lh-parallel -c 3 -d desktop
